server:
  servlet:
    context-path: /blog
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: '1.0'

delete:
  secret: ${DELETE_SECRET}

logs:
  path: ${LOG_PATH:logs/}

springdoc:
  api-docs:
    enabled: true
    path: /api/swagger
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    path: /ui/swagger
    operations-sorter: alpha
  packages-to-scan: com.codenjoy.blog.controller

management:
  endpoints:
    web:
      exposure:
        include: health,info