-- do it by hand

-- CREATE USER apofig WITH PASSWORD 'apofig';
-- GRANT USAGE ON SCHEMA public TO apofig;
-- GRANT CREATE ON SCHEMA public TO apofig;
-- GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO apofig;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO apofig;